var annotated_dup =
[
    [ "TowerVR", "namespace_tower_v_r.html", "namespace_tower_v_r" ],
    [ "Vuforia", "namespace_vuforia.html", "namespace_vuforia" ],
    [ "ConnectAndCreateTowerManager", "class_connect_and_create_tower_manager.html", null ],
    [ "ConnectAndJoinTest", "class_connect_and_join_test.html", "class_connect_and_join_test" ],
    [ "CreateNewGame", "class_create_new_game.html", "class_create_new_game" ],
    [ "Fading", "class_fading.html", "class_fading" ],
    [ "FPSDisplay", "class_f_p_s_display.html", null ],
    [ "GazeOver", "class_gaze_over.html", "class_gaze_over" ],
    [ "JoinServer", "class_join_server.html", "class_join_server" ],
    [ "MasterClientOnlyBehaviour", "class_master_client_only_behaviour.html", null ],
    [ "NetworkedBehaviour", "class_networked_behaviour.html", null ],
    [ "PhotonNetworkEvent", "class_photon_network_event.html", "class_photon_network_event" ],
    [ "PlayerCameraMovement", "class_player_camera_movement.html", "class_player_camera_movement" ],
    [ "RandomizeServerName", "class_randomize_server_name.html", null ],
    [ "removeTargetChild", "classremove_target_child.html", null ],
    [ "RestrictToHost", "class_restrict_to_host.html", "class_restrict_to_host" ],
    [ "RetrieveAndSpawnPlayers", "class_retrieve_and_spawn_players.html", "class_retrieve_and_spawn_players" ],
    [ "SceneTransitionManager", "class_scene_transition_manager.html", "class_scene_transition_manager" ],
    [ "SetMaxPlayers", "class_set_max_players.html", "class_set_max_players" ],
    [ "ShowServers", "class_show_servers.html", "class_show_servers" ],
    [ "Singleton", "class_singleton.html", null ],
    [ "SpawnSelectedLevel", "class_spawn_selected_level.html", "class_spawn_selected_level" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "Torus", "class_torus.html", "class_torus" ],
    [ "TorusGenerator", "class_torus_generator.html", "class_torus_generator" ],
    [ "TransformDebugger", "class_transform_debugger.html", "class_transform_debugger" ]
];