var namespace_tower_v_r =
[
    [ "FallingTowerDetection", "class_tower_v_r_1_1_falling_tower_detection.html", null ],
    [ "GameState", "class_tower_v_r_1_1_game_state.html", "class_tower_v_r_1_1_game_state" ],
    [ "GameStateChangedEvent", "class_tower_v_r_1_1_game_state_changed_event.html", "class_tower_v_r_1_1_game_state_changed_event" ],
    [ "HandleEndGame", "class_tower_v_r_1_1_handle_end_game.html", "class_tower_v_r_1_1_handle_end_game" ],
    [ "HandleStartGame", "class_tower_v_r_1_1_handle_start_game.html", "class_tower_v_r_1_1_handle_start_game" ],
    [ "IncreaseHeight", "class_tower_v_r_1_1_increase_height.html", null ],
    [ "ITowerGameManager", "interface_tower_v_r_1_1_i_tower_game_manager.html", "interface_tower_v_r_1_1_i_tower_game_manager" ],
    [ "MasterClientOnlyBehaviour", "class_tower_v_r_1_1_master_client_only_behaviour.html", null ],
    [ "MasterTowerGameManagerImpl", "class_tower_v_r_1_1_master_tower_game_manager_impl.html", "class_tower_v_r_1_1_master_tower_game_manager_impl" ],
    [ "NetworkEventCodes", "class_tower_v_r_1_1_network_event_codes.html", "class_tower_v_r_1_1_network_event_codes" ],
    [ "NextPlayerEvent", "class_tower_v_r_1_1_next_player_event.html", "class_tower_v_r_1_1_next_player_event" ],
    [ "PlaceTowerPieceEvent", "class_tower_v_r_1_1_place_tower_piece_event.html", "class_tower_v_r_1_1_place_tower_piece_event" ],
    [ "PlacingBricks", "class_tower_v_r_1_1_placing_bricks.html", "class_tower_v_r_1_1_placing_bricks" ],
    [ "PlayerLostEvent", "class_tower_v_r_1_1_player_lost_event.html", "class_tower_v_r_1_1_player_lost_event" ],
    [ "PlayerReadyEvent", "class_tower_v_r_1_1_player_ready_event.html", "class_tower_v_r_1_1_player_ready_event" ],
    [ "PlayerTurnObserver", "class_tower_v_r_1_1_player_turn_observer.html", null ],
    [ "PlayerWonEvent", "class_tower_v_r_1_1_player_won_event.html", "class_tower_v_r_1_1_player_won_event" ],
    [ "Score", "struct_tower_v_r_1_1_score.html", "struct_tower_v_r_1_1_score" ],
    [ "ScoreChangedEvent", "class_tower_v_r_1_1_score_changed_event.html", "class_tower_v_r_1_1_score_changed_event" ],
    [ "SelectTowerPieceEvent", "class_tower_v_r_1_1_select_tower_piece_event.html", "class_tower_v_r_1_1_select_tower_piece_event" ],
    [ "TowerConstants", "class_tower_v_r_1_1_tower_constants.html", "class_tower_v_r_1_1_tower_constants" ],
    [ "TowerGameBehaviour", "class_tower_v_r_1_1_tower_game_behaviour.html", "class_tower_v_r_1_1_tower_game_behaviour" ],
    [ "TowerGameManager", "class_tower_v_r_1_1_tower_game_manager.html", "class_tower_v_r_1_1_tower_game_manager" ],
    [ "TowerGameManagerImpl", "class_tower_v_r_1_1_tower_game_manager_impl.html", "class_tower_v_r_1_1_tower_game_manager_impl" ],
    [ "TowerPiece", "class_tower_v_r_1_1_tower_piece.html", null ],
    [ "TowerState", "class_tower_v_r_1_1_tower_state.html", "class_tower_v_r_1_1_tower_state" ],
    [ "TowerStateChangedEvent", "class_tower_v_r_1_1_tower_state_changed_event.html", "class_tower_v_r_1_1_tower_state_changed_event" ],
    [ "TryStartGameEvent", "class_tower_v_r_1_1_try_start_game_event.html", "class_tower_v_r_1_1_try_start_game_event" ],
    [ "TurnState", "class_tower_v_r_1_1_turn_state.html", "class_tower_v_r_1_1_turn_state" ],
    [ "TurnStateChangedEvent", "class_tower_v_r_1_1_turn_state_changed_event.html", "class_tower_v_r_1_1_turn_state_changed_event" ],
    [ "TurnTimeLimits", "class_tower_v_r_1_1_turn_time_limits.html", "class_tower_v_r_1_1_turn_time_limits" ]
];